model:
  name: 'da3'
  attention: 'normal' # 'normal', 'hard'
  af_lambd: 0.02
  embed_dim: 64
  patch_size: 1
  block_loop: 1
  num_heads: 4
  mlp_ratio: 4

  hidden_layer_sizes: [128]
  fc_afs: ['relu']

  hidden_channels: [32]
  output_channel: 64
  hidden_kernels: [2, 2]
  hidden_strides: [1, 1]
  conv_afs: ['max_pool2d', 'max_pool2d']
  af_kernels: [2, 2]
  af_strides: [2, 2]
